GET http://localhost:9000/users

###
POST http://localhost:9000/api/users/signup
Content-Type: application/json

{   
    "fullname": "John Doe",
    "password": "123456",
    "username": "johndoe"
}

###
POST http://localhost:9000/api/users/login
Content-Type: application/application/json

{
    "username": "janede",
    "password": "123456"
}
