GET http://localhost:9000/api/users/info?id=9e60ed49-4eb7-4a2c-8481-af906e5d05a1

###
POST http://localhost:9000/api/users/signup
Content-Type: application/json

{   
    "fullname": "John Doe",
    "password": "123456",
    "username": "johndoe"
}

###
POST http://localhost:9000/api/users/login
Content-Type: application/application/json

{
    "username": "janede",
    "password": "123456"
}
