GET http://localhost:9000/api/users/info?id=5ce886e6-6020-4456-83ca-3674b403edde

###
POST http://localhost:9000/api/users/signup
Content-Type: application/json

{   
    "fullname": "Ricardo Leiva",
    "password": "123456",
    "username": "ricardo2002"
}

###
POST http://localhost:9000/api/users/login
Content-Type: application/application/json

{
    "username": "johndoe",
    "password": "123456"
}
